doclist = ("Copy","Feedback","Rating","Problem","Queries","Quotes","Questions",
           "Support","Tracking","Release","Goal","Schedule","Model","Description",
           "Dev","Development","All","Environment","Error","Codes","Keys","FAQs",
           "Summary","Task","Requirements","Flow","Details","Roadmap","Application",
           "Checklist","License","Benchmark","CIO","CFO","CEO","COO","CTO","Report",
           "Cloud","Comparison","Marketing","Finance","Promotion","Example","File",
           "College","Expenses","Task","Profiles","Recommendations","Misc","Materials",
           "Tradeshow","Reseller","Customer","Agreement","Auditing","Access",
           "Events","Buyer","Purchase","Order","Product","Strategy","Beta","Design",
           "Plan","Weekly","Daily","Monthly","Yearly","Campaign","Data","Contract",
           "Salary","Benefits","Insurance","Draft","Final","Calendar","Whitepaper",
           "Scenarios","Sales","Resume","Program","Form","Management","Usage","Partner",
           "Test","Use Case","Tracking","Bonuses","1x1","Business","Directory","Review",
           "Template","Employees","List","Feature","Status","Security","Overview",
           "Priorities","Lifecycle","Analysis","Activation","Folder","Free","User",
           "Premium","General","Leads","Agenda","Sheet","Work","Hours","Content","Asset",
           "Hires","Pipeline","Industry","Stock","Option","Investors","Network",
           "Interview","Job","Patch","Release","Launch","Prospects","Diagram","Layout",
           "Proposal","Metrics","Trial","2010","2011","2009","Future","Notes","New",
           "Rules","Research","Invoice","January","February","March","April","May",
           "June","July","August","September","November","December","Cost","Performance",
           "PR","Public","Policy","Operations","IT","Q1","Q2","Q3","Q4","QA","Quality",
           "Consultant","Meeting","Bugs","Monday","Tuesday","Wednesday","Thursday",
           "Friday","Temp","Revision")